url    : "https://www.homeloansandbonds.co.za"
baseurl: ""

title      : Homeloans and Bonds
email      : info@homeloansandbonds.co.za
description: Let Homeloans and Bonds get you the best deal on your homeloan. We will get comparative quotes from the banks to secure a homeloan at the best rate. Home buyers and first time home buyers trust us with getting the best bond.
author     : 

analytics:
  google: G-9CQQ2N9SGF

collections:
  portfolio: 

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/img/logo.png