url    : "https://www.homeloansandbonds.co.za"
baseurl: ""

title      : Homeloans and Bonds
email      : nola@homeloansandbonds.co.za
description: Let Homeloans and Bonds get you the best deal on your homeloan. We provide comparative quotes from the banks. Home buyers and first time home buyers trust us to secure their homeloans at the best rate.
author     : 

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio: 

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/img/logo.png